# Generated by Django 3.2.9 on 2021-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDayReminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('dateofbirth', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Birthday-Reminders',
            },
        ),
    ]
